name: ml_dl_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - notebook
  - pip
  - pip:
      - yfinance
      - tensorflow
      - keras
      - torch
      - torchvision
      - torchaudio
      - xgboost
      - lightgbm
      - catboost
      - statsmodels
      - transformers
      - optuna
      - mlflow
      - fastai
